export const services = [
    {
      id: 1,
      image: '/assets/img/gestion-de-redes-sociales.jpg',
      title: 'GESTIÓN DE REDES SOCIALES',
      description: 'Planifico, publico y mantengo activa tu presencia en redes como Instagram, Facebook, TikTok y LinkedIn.',
      textColor: '#6b6b6b',
      backgroundColor: '#6b6b6b',
    },
    {
      id: 2,
      image: '/assets/img/parrilla.jpg',
      title: 'PARRILLA DE CONTENIDOS',
      description: 'Creo y organizo el contenido que publicarás en tus redes sociales.',
      textColor: '#355C7D',
      backgroundColor: '#355C7D',
    },
    {
      id: 3,
      image: '/assets/img/redaccion-de-blogs.jpg',
      title: 'REDACCIÓN DE BLOGS',
      description: 'Creo artículos pensados para educar, atraer y posicionar tu marca con un enfoque SEO.',
      textColor: '#e57373',
      backgroundColor: '#e57373',
    },
    {
      id: 4,
      image: '/assets/img/email-marketing.jpg',
      title: 'EMAIL MARKETING',
      description: 'Diseño y envío de correos estratégicos para fidelizar a tu audiencia, promocionar servicios y mantener una comunicación directa y profesional.',
      textColor: '#e57373',
      backgroundColor: '#6b6b6b',
    },
    {
      id: 5,
      image: '/assets/img/publicidad-en-redes-sociales.jpg',
      title: 'PUBLICIDAD EN REDES SOCIALES',
      description: 'Creo, configuro y optimizo campañas publicitarias para aumentar tu alcance y atraer más clientes.',
      textColor: '#6b6b6b',
      backgroundColor: '#355C7D',
    },
    {
      id: 6,
      image: '/assets/img/pagina-web.jpg',
      title: 'CREACIÓN Y MANTENIMIENTO DE PÁGINAS WEB',
      description: 'Para que siempre luzca profesional, funcione bien y esté actualizada.',
      textColor: '#355C7D',
      backgroundColor: '#e57373',
    },
  ];